# pipeline describes build steps
pipeline:
  # every entry in the pipeline describes a single build step
  # you can use any name for the step
  test:
    # image used to create a container
    image: golang:1.8-alpine
    # commands executed in the container
    commands:
      - "go test"

  build:
    image: golang:1.8-alpine
    # you can additionally specify environment variables
    environment:
      CGO_ENABLED: "0"
      VERSION: "${DRONE_TAG}"
      COMMIT: "${DRONE_COMMIT_SHA:0:7}"
    commands:
      - "go build -o ./myapp"
  publish:
    image: plugins/docker
    repo: skolodyazhnyy/myapp
